name: Feature request
description: Suggest a new idea.
labels: ['enhancement', 'triage']
body:
    - type: markdown
      attributes:
          value: |
              Please provide a searchable summary of the issue in the title above.

              Thanks for contributing by creating an issue!
    - type: checkboxes
      attributes:
          label: Duplicates
          description: Please [search the history](https://github.com/norma-uy/template-symfony-cms/issues) to see if an issue already exists for the same problem.
          options:
              - label: I have searched the existing issues
                required: true
    - type: checkboxes
      attributes:
          label: Latest version
          description: We roll bug fixes, performance enhancements, and other improvements into new releases.
          options:
              - label: I have tested the latest version
                required: true
    - type: textarea
      attributes:
          label: Summary
          description: Describe how it should work.
    - type: textarea
      attributes:
          label: Examples
          description: Please provide a link to other implementations or screenshots of the expected behavior.
    - type: textarea
      attributes:
          label: Motivation
          description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
